language: python
python:
  - "3.6"
  
# command to install dependencies
install:
  - pip install -r requirements.txt

# Setting environment variables
env:
  - ENV_VAR=testing
  - ENV_VAR2=development
  - ENV_VAR3=production

# create a db named test
before_script:
  - psql -c 'create database test;' -U postgres

# command to run tests
script:
  - pytest --cov-report term --cov=app

after_success:
  - coveralls