language: python
python:
  - "3.6"
  
# command to install dependencies
install:
  - pip install -r requirements.txt

# Setting environment variables
env:
  - ENV_VAR=testing

# create a db named test
before_script:
  - psql -c 'create database test_db;' -U postgres

# command to run tests
script:
  - pytest --cov-report term --cov=app
  # - python -m unittest

after_success:
  - coveralls