version: "3"
services:
  web:
    restart: always
    build: .
    container_name: recipeapi
    image: gcr.io/${GCP_PROJECT_ID}/recipeapi:$IMG_TAG
    ports:
      - "80:80"
    environment:
      FLASK_CONFIG: "${FLASK_CONFIG}"
      SECRET_KEY: "${SECRET_KEY}"
    volumes:
      - ".:/app"
