version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    name: recipeapi
    command: python3 manage.py runserver
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db