version: '3'
services:
  web:
    restart: always
    build: .
    container_name: recipeapi
    image: thegaijin/recipeapi
    ports:
      - '80:80'
    environment:
      FLASK_CONFIG: 'development'
      SECRET_KEY: 'efgdhnhmjfdb'
    volumes:
      - '.:/app'
