version: '3'
services:
  web:
    restart: always
    build: .
    ports:
      - '80:80'
    environment:
      FLASK_APP: '${FLASK_APP}'
      FLASK_CONFIG: '${FLASK_CONFIG}'
      SECRET_KEY: '${SECRET_KEY}'
    volumes:
      - '.:/app'
