apiVersion: batch/v1
kind: Job
metadata:
  name: recipeapi-migrations-job
  namespace: default
spec:
  template:
    metadata:
      name: recipeapi-migrations-job
    spec:
      containers:
        - name: recipeapi-migrations
          image: gcr.io/{{ GCP_PROJECT_ID }}/recipeapi:{{ IMG_TAG }}
          command: ["/bin/sh","-c"]
          args: ["python3 manage.py db init; python3 manage.py db migrate && python3 manage.py db upgrade"]
          env:
            - name: FLASK_CONFIG
              value: "{{ FLASK_CONFIG }}"
            - name: DATABASE_URL
              value: "{{ DATABASE_URL }}"
      restartPolicy: Never
