default: &defaults
  docker:
    - image: "thegaijin/cc-python-k8ps:v2"
      environment:
        FLASK_CONFIG: testing
        TEST_DATABASE_URL: "postgresql://ubuntu@localhost/circle_test?sslmode=disable"
    - image: "circleci/postgres:9.6.5-alpine-ram"
      environment:
        POSTGRES_USER: circleci
        POSTGRES_DB: test_db
        POSTGRES_PASSWORD: ""
  working_directory: ~/project

cmd_attach_workspace: &cmd_attach_workspace
  attach_workspace:
    at: ~/project

cmd_install_packages: &cmd_install_packages
  run:
    command: |
      python3 -m venv venv
      . venv/bin/activate
      pip install -r requirements.txt

cmd_save_cache: &cmd_save_cache
  save_cache:
    key: api-dependencies-{{ checksum "Pipfile.lock" }}
    paths:
      - $(python3 -m venv venv)

cmd_restore_cache: &cmd_restore_cache
  restore_cache:
    key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

cmd_login_gcp: &cmd_login_gcp
  run:
    name: login into GCP
    command: |
      echo "Service account"
      echo ${SERVICE_ACCOUNT}
      echo "GCP Project ID"
      echo $GCP_PROJECT_ID
      chmod +x .circleci/gcp_login.sh
      .circleci/gcp_login.sh main

cmd_build_and_push_docker: &cmd_build_and_push_docker
  run:
    name: build image
    command: |
      export IMG_TAG=$(echo $CIRCLE_SHA1 | cut -c -7)
      echo $IMG_TAG
      docker login -u _json_key -p "$(echo $SERVICE_ACCOUNT)" https://gcr.io
      docker-compose up -d
      docker push gcr.io/${GCP_PROJECT_ID}/recipeapi:$IMG_TAG
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *cmd_attach_workspace
      - *cmd_install_packages
      - *cmd_save_cache

  test:
    <<: *defaults
    steps:
      - checkout
      - *cmd_attach_workspace
      - *cmd_install_packages
      - run: mkdir test-reports
      - run:
          command: |
            . venv/bin/activate
            pytest
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
  deploy:
    docker:
      - image: "thegaijin/cc-python-k8ps:v2"
        auth:
          username: _json_key
          password: $SERVICE_ACCOUNT
        environment:
          FLASK_CONFIG: ${FLASK_CONFIG}
          SECRET_KEY: ${SECRET_KEY}
          GOOGLE_APPLICATION_CREDENTIALS: /root/project/shared/account.json
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - *cmd_attach_workspace
      - *cmd_login_gcp
      - *cmd_build_and_push_docker
      - run:
          name: deploy app
          command: |
            echo ${CLUSTER_NAME}
            cd k8s
            ansible-playbook playbook.yml --extra-vars "@vars.yml" -vvv
    working_directory: ~/project

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - deployment
                - develop
                - master
