version: 2
jobs:
  build:
    docker:
      - image: 'circleci/python:3.6.2-stretch-browsers'
        environment:
          FLASK_CONFIG: testing
          TEST_DATABASE_URL: 'postgresql://ubuntu@localhost/circle_test?sslmode=disable'
      - image: 'circleci/postgres:9.6.5-alpine-ram'
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: test_db
          POSTGRES_PASSWORD: ''
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: >
            curl -O
            http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: >
            java -jar selenium-server-standalone-3.5.3.jar -log
            test-reports/selenium.log
          background: true
      - restore_cache:
          key: 'deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}'
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install awscli
      - run:
          command: |
            . venv/bin/activate
            pip3 install awscli
            pytest
      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            ls -la
            pwd
            docker-compose up
            docker-compose push
      - run:
          name: Install aws cli
          command: sudo apt-get -y -qq install awscli
