apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: recipeapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: recipeapi
    spec:
      containers:
        - name: apache
          image: thegaijin/recipeapi
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: recipeapi
  labels:
    app: recipeapi
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31818
  selector:
    app: recipeapi
