PROJECT_NAME: "{{ lookup('env', 'PROJECT_NAME') }}"
IMG_TAG: "{{ lookup('env', 'IMG_TAG') }}"
GCP_PROJECT_ID: "{{ lookup('env', 'GCP_PROJECT_ID') }}"
DATABASE_URL: "{{ lookup('env', 'DATABASE_URL') }}"
FLASK_CONFIG: "{{ lookup('env', 'FLASK_CONFIG') }}"
SECRET_KEY: "{{ lookup('env', 'SECRET_KEY') }}"
