---
apiVersion: v1
kind: Service
metadata:
  name: recipeapi
  namespace: default
  labels:
    app: recipeapi
spec:
  selector:
    app: recipeapi
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
...
