apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: recipeapi
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: recipeapi
    spec:
      containers:
      - command:
        - python
        - manage.py
        - runserver
        env:
          - name: FLASK_CONFIG
            value: "{{ FLASK_CONFIG }}"
          - name: SECRET_KEY
            value: "{{ SECRET_KEY }}"
          - name: DATABASE_URL
            value: "{{ DATABASE_URL }}"
        image: gcr.io/${GCP_PROJECT_ID}/recipeapi:{{ IMG_TAG }}
        name: recipeapi
        imagePullPolicy: Always
        ports:
          - containerPort: 80
